services:
  postgres:
    image: postgres:18
    container_name: dtc_db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dtc
    ports:
      - "5434:5432"

    volumes:
      - postgres_data:/var/lib/postgresql

  pgadmin:
    image: dpage/pgadmin4:latest

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dtc.com
      PGADMIN_DEFAULT_PASSWORD: admin

    ports:
      - "8080:80"

    depends_on:
      - postgres

volumes:
  postgres_data:

